### ISSUE TITLE
Why are you forcing install the prerequires?

### ISSUE THREAD

**Issue by MuscularPuky** [programmer2514/DPEdit-GUI#4]
and Why do not you use wizard?

at least it needs to has kind of a form or window not a dialog

why are you forcing reinstall the prerequires?? 

I already have Python 3 and VC 2015-2021

and I do not want to any downgrade the major version is same so do not need to downgrade

and Why are you running the installer vc_redist.exe in slient/quiet mode??

It force-restarts my PC without ANY dialog or alert even after 5 min of I launched DPEdi-GUI and end the task because it does not display or prompt ANYTHNG so I ended

Next time it had better make the installer checks the prerequires is already installed

and does not restart one's PC without any confirm too,

lastly displays installation progress

**Comment by programmer2514** [comment]
> Why are you running the installer vc_redist.exe in slient/quiet mode?? It force-restarts my PC without ANY dialog or alert

I will get on fixing this, as it _definitely_ should not be doing that.

Also, the installer _does_ check if you have the prerequisites installed and should not prompt you to install them if it is capable of successfully running the script using pyw.exe. Are you certain that your Python installation is added to PATH? If not, the installer has no way of knowing where it is and will think it is not installed.

Additionally, your Python installation must be standard, and not missing default packages such as Tkinter. I will attempt to add some more verbosity to the installer so it explains why it was unable to successfully initialize the script in the next release, but for the time being, what happens if you just run bin/dpedit_gui.py directly from your Python IDE?

**Comment by programmer2514** [comment]
**UPDATE:**
It appears that your specific issue is caused by a local Python installation, or one which is missing the py.exe launcher (these are both options you can set when installing). I am nearly certain that the updated launcher has fixed the computer restart and broken Python issues, so if you let it do its thing, it should work now.

If you would prefer to stick with a custom-installed Python version instead, you will need to re-install Python, making sure that "Add python.exe to PATH" and "Use admin privileges when installing py.exe" are both checked. They are not by default, and without those features, DPEdit GUI will not work.

**Comment by MuscularPuky** [comment]
> > Why are you running the installer vc_redist.exe in slient/quiet mode?? It force-restarts my PC without ANY dialog or alert
> 
> I will get on fixing this, as it _definitely_ should not be doing that.
> 
> Also, the installer _does_ check if you have the prerequisites installed and should not prompt you to install them if it is capable of successfully running the script using pyw.exe. Are you certain that your Python installation is added to PATH? If not, the installer has no way of knowing where it is and will think it is not installed.
> 
> Additionally, your Python installation must be standard, and not missing default packages such as Tkinter. I will attempt to add some more verbosity to the installer so it explains why it was unable to successfully initialize the script in the next release, but for the time being, what happens if you just run bin/dpedit_gui.py directly from your Python IDE?

Sorry for my tantrums. My Python is UWP version and in `%ProgramFiles%\WindowsApps\(Package GUID)` and `%LocalAppData%\Microsoft\WindowsApps`
Perhaps installer can't notice that Python is installed because is packaged

**Comment by MuscularPuky** [comment]
> **UPDATE:** It appears that your specific issue is caused by a local Python installation, or one which is missing the py.exe launcher (these are both options you can set when installing). I am nearly certain that the updated launcher has fixed the computer restart and broken Python issues, so if you let it do its thing, it should work now.
> 
> If you would prefer to stick with a custom-installed Python version instead, you will need to re-install Python, making sure that "Add python.exe to PATH" and "Use admin privileges when installing py.exe" are both checked. They are not by default, and without those features, DPEdit GUI will not work.

+as I knwo, the UWP version of Python does not provide any installer wizard and always work as silent/quiet mode because MS Store should work like Play Store so I can't configure its installation option unfortunately
Moreover UWP Python does not set the path as environment variable and does set it as Deep Link in %LocalAppData% like .exes in System32 because it's packaged
Should I reinstall my Python as Win32?

**Comment by programmer2514** [comment]
Yes, that should indeed fix the issue - you can get it directly from [python.org](https://www.python.org/downloads/) or you can use the DPEdit-GUI executable, which in theory should be identical to installing it yourself (it just downloads the latest version from python.org and installs it).

You are correct that Python as a UWP app is quite difficult to detect and run reliably from a 3rd-party application, as all Windows Store apps are _completely_ sandboxed - not even a program running as Administrator is capable of accessing their files. I have in the past tinkered with UWP apps, and in order to even see their files, most times you must be running as TrustedInstaller - something I would rather not make DPEdit do as to do so would be quite invasive and insecure.
